FROM wordpress:5.8.3-php7.4-fpm

WORKDIR /var/www/html

# Add utils
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nano \
        bash \
        curl \
    && rm -rf /var/lib/apt/lists/*
