FROM wordpress:5.8.3-php7.4-fpm-alpine

WORKDIR /var/www/html

# Add utils
RUN apk update && apk add --no-cache nano bash curl

# xdebug
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS} \ 
    && pecl install xdebug-3.1.6 \
    && docker-php-ext-enable xdebug
RUN  echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    # && echo "xdebug.client_host=172.25.0.1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini